// File generated by Antigravity based on user provided plist
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5pQoVwrUdgG3F6wdDyoW_2YHixdKVZIU',
    appId: '1:868473732972:ios:30a49f38c511f7246b3d49',
    messagingSenderId: '868473732972',
    projectId: 'chat-days',
    storageBucket: 'chat-days.firebasestorage.app',
    iosBundleId: 'com.ichihos.cheatdays',
    iosClientId:
        '868473732972-qmsvg7mu6umucccr90n44nslcj5dpgji.apps.googleusercontent.com',
  );

  // Web configuration - you may need to create a web app in Firebase Console
  // and update these values with the actual ones from your Firebase project
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5pQoVwrUdgG3F6wdDyoW_2YHixdKVZIU',
    appId: '1:868473732972:web:a54d71297db30cc66b3d49',
    messagingSenderId: '868473732972',
    projectId: 'chat-days',
    storageBucket: 'chat-days.firebasestorage.app',
    authDomain: 'chat-days.firebaseapp.com',
  );
}
