import 'dart:convert';
import 'package:cheat_days/features/recipes/data/recipe_repository.dart';
import 'package:cheat_days/features/recipes/domain/recipe.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:uuid/uuid.dart';

class JsonImportScreen extends ConsumerStatefulWidget {
  const JsonImportScreen({super.key});

  @override
  ConsumerState<JsonImportScreen> createState() => _JsonImportScreenState();
}

class _JsonImportScreenState extends ConsumerState<JsonImportScreen> {
  final TextEditingController _controller = TextEditingController();
  bool _isLoading = false;
  String? _statusMessage;

  Future<void> _importJson() async {
    setState(() {
      _isLoading = true;
      _statusMessage = null;
    });

    try {
      final List<dynamic> jsonList = jsonDecode(_controller.text);
      final repository = ref.read(recipeRepositoryProvider);

      int successCount = 0;

      for (var item in jsonList) {
        // Basic validation/conversion
        try {
          // Adjust fields if necessary to match Recipe model expects or handle missing fields
          // Assuming JSON structure matches what we expect from the LLM prompt in spec:
          /*
              {
                "name": "...",
                "category": "...",
                "timeMinutes": 30,
                "costYen": 500,
                "ingredients": [...],
                ...
              }
             */

          // We need to map ingredients from JSON structure to our Ingredient model if slightly different
          // But let's assume strict adherence or flexible map usage.
          // Since we need to create a Recipe object or just pass Map to firestore?
          // Repository has addRecipe(Recipe). Let's convert to Recipe.
          // But ID is generated by firestore generally, or we provide one.
          // Let's rely on Repository.addRecipe to add a new doc.
          // Wait, Repository.addRecipe takes a Recipe object which requires an ID.
          // We should ideally change repository to accept data map or generate ID here.

          final docId =
              const Uuid()
                  .v4(); // Generate a temp ID for local object construction

          // Map JSON ingredients to Ingredient objects
          final ingredients =
              (item['ingredients'] as List)
                  .map(
                    (i) => Ingredient(
                      name: i['name'],
                      amount: i['amount'].toString(),
                      unit: i['unit'],
                      isMain: i['isMain'] ?? false,
                    ),
                  )
                  .toList();

          final recipe = Recipe(
            id: docId, // Will be ignored by add() if we use .add(), but let's check repo implementation
            name: item['name'],
            imageUrl:
                item['imageUrl'] ??
                'https://placehold.co/600x400/orange/white?text=No+Image',
            category: item['category'] ?? 'main',
            cuisine: item['cuisine'] ?? 'other',
            timeMinutes:
                item['timeMinutes'] is int
                    ? item['timeMinutes']
                    : int.tryParse(item['timeMinutes'].toString()) ?? 0,
            costYen:
                item['costYen'] is int
                    ? item['costYen']
                    : int.tryParse(item['costYen'].toString()) ?? 0,
            difficulty: item['difficulty'] ?? 1,
            seasons: List<String>.from(item['seasons'] ?? []),
            calories: item['calories'],
            ingredients: ingredients,
            steps: List<String>.from(item['steps'] ?? []),
            tags: List<String>.from(item['tags'] ?? []),
            createdAt: DateTime.now(),
          );

          await repository.addRecipe(recipe);
          successCount++;
        } catch (e) {
          print("Skipping item due to error: $e");
        }
      }

      setState(() {
        _statusMessage = "インポート完了: $successCount 件";
      });
    } catch (e) {
      setState(() {
        _statusMessage = "JSONパースエラー: $e";
      });
    } finally {
      setState(() {
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("レシピJSONインポート")),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            const Text("AIで生成したレシピJSON配列を貼り付けてください"),
            const SizedBox(height: 8),
            Expanded(
              child: TextField(
                controller: _controller,
                maxLines: null,
                expands: true,
                decoration: const InputDecoration(
                  border: OutlineInputBorder(),
                  hintText: '[ { "name": "...", ... }, ... ]',
                ),
              ),
            ),
            const SizedBox(height: 16),
            if (_statusMessage != null) ...[
              Text(
                _statusMessage!,
                style: TextStyle(
                  color:
                      _statusMessage!.contains("エラー")
                          ? Colors.red
                          : Colors.green,
                ),
              ),
              const SizedBox(height: 16),
            ],
            SizedBox(
              width: double.infinity,
              child: ElevatedButton(
                onPressed: _isLoading ? null : _importJson,
                child:
                    _isLoading
                        ? const CircularProgressIndicator()
                        : const Text("インポート実行"),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
